# Generated by Django 5.2 on 2025-05-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('concert_id', models.AutoField(primary_key=True, serialize=False)),
                ('konser_adi', models.CharField(max_length=200)),
                ('sehir_id', models.IntegerField()),
                ('adres', models.CharField(max_length=255)),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('fiyat', models.IntegerField()),
                ('mekan', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('soyisim', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('yas', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('bakiye', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.concert')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
